### ISSUE TITLE
payment attempt not completed before timeout

### ISSUE THREAD

**Issue by cj-chua** [lnproxy/lnproxy-relay#21]
Tried to pay multiple wrapped invoices using both WOS and BlueWallet, only one payment succeeded. Is this error related to  https://github.com/lnproxy/lnproxy/issues/14 ?

LND logs is not very descriptive...
```
2023-05-02 05:16:07.414 [WRN] CRTR: payment attempt not completed before timeout
2023-05-02 05:16:07.426 [ERR] CRTR: Payment 4531b1e759fe0db95b076bb0d677f42b7ea7644e6007ac22b40eb65a8c0f9ffa failed: timeout
```

**Comment by lnproxy** [comment]
Hard to say.  I would guess it's fee related, how big were the payments?  Did you use a custom routing budget?

**Comment by cj-chua** [comment]
More context: the payment fails almost immediately, and I'm calling the `Wrap` func

The payments were just 10 sats, no custom routing budget

**Comment by cj-chua** [comment]
Just tried wrapping 2 invoices with the node on lnproxy.org, they failed as well. Here are the invoices
```
lnbc110900p1pj9rf36pp5v5sr6fgt6p7qf2fua034fkeqkhhry6xxjmhy7mstvxx7m0mtgk2qdqqcqz0rxqyz5ztsp5jrejz8h7l4nj6ejkffr8f69uxqtvzrdu6djuynrse3jnmh9kgt5q9qyyssq8l3vmvdckvyq5yy5nq352hvs0cmsa7c7vl40drj5jmvhtapp7seze5t2nwg9vt3auny3re5r2wksfddxjgr0t5wwdjth06n60hvejuqqq0zwxf

lnbc110900p1pj9rfd9pp5qcm23w3q2fnhs7sjtxrkyjusecy5seq6dm0sum0mm3xuq8vn72dsdqqcqz0rxqyz5z2sp5d484cgc8vsu4mz9mmm60yqu4c37wae5ywjkz8jks9g7qr6qevkxs9qyyssq200mq82slwtskypcanu57p4xj4lt5w9rclvv6ts5hsq00ukndgzn67upwt9lwd956gjhpe6wvtv9acgfv9mg5vkh3gvynqkdh9d9g6qpvchfnk
```
The node of the original invoice: 03501a74753e0f6ae270a1e4e2ffbbc37f7a796360e650c1121c18e116b22ac106
They were paid using WOS

@lnproxy do you own the wrapper node? Any chance you could look into the logs and see if we had the same error message?

**Comment by lnproxy** [comment]
Looks like the initial payments to the relay went through, but the relay was not able to pay the original destination:
```
"failure_reason": "FAILURE_REASON_NO_ROUTE"
```
This is usually because the fee budget is too low.  In this case it's almost certainly because you wrapped 10 sat invoices and, by default, that only adds a 1.09 sat routing budget.  The relay couldn't find a path to the original destination that only charged 1.09 sat.

If you try a 1000 sat invoice the default routing budget will be 10 sats which should be plenty to reach your node.  Alternatively, you can use a 10 sat invoice again and hit the drop-down menu for advanced options and specify a higher budget, 2-4 sats should be about right.

**Comment by cj-chua** [comment]
```
lnbc1100n1pj9rd6tpp5gzlqn4dz8k8grq97t7kdcvpn0n99sdvwpqjlfvgesplvzj38mu6qdqqcqz0rxqr284sp5xh0jxed5xcpgyg99ggn755lr0j3g83avkysxmy3t5kuetvms0cfs9qyyssqa5zqt8ggwqpkyfk725nxh69x3asxmp58srfq4rl3c4d8a3hrx9tjcuu83nqjcqdzudgemx93epnyz4rlygxsaeds75qrfy0u0eme2sgq86qma4
```
Just tried with a 10sat invoice with 100sat routing budget, still no luck. This time paid with Alby

**Comment by cj-chua** [comment]
might have found something: Is this line the culprit?
https://github.com/lnproxy/lnproxy/blob/main/lnproxy.go#L324

it's giving a negative value. It's supposed to be just `p.Expiry` ?

**Comment by lnproxy** [comment]
> Just tried with a 10sat invoice with 100sat routing budget, still no luck. This time paid with Alby

hmm, I guess that invalidates my earlier hypothesis.  Maybe lnd's mission control got weird after the failed attempts.  I've reset it.


> might have found something: Is this line the culprit? https://github.com/lnproxy/lnproxy/blob/main/lnproxy.go#L324
> 
> it's giving a negative value. It's supposed to be just `p.Expiry` ?

Yeah, that should not be negative.  I'm not sure it's necessary either, since the relay already has the htlc for the original invoice at this point, the cltv limit should be enough.  I'll do some debugging and get back to you ASAP.

Thank you so much for bringing this to my attention

**Comment by cj-chua** [comment]
No problem at all. Just a FYI, I created this https://github.com/lnproxy/lnproxy/pull/22 . With this change things are starting to work for me

**Comment by lnproxy** [comment]
Merged.  You were absolutely right.  I'm surprised it still worked some of the time!

**Comment by cj-chua** [comment]
I'm surprised too. What is the best platform to reach you? I have some questions about I would like to discuss with you

**Comment by lnproxy** [comment]
Sent you a DM on nostr
