### ISSUE TITLE
Idea: Combine LNProxy with LN Address Bridge

### ISSUE THREAD

**Issue by bitcoinheiro** [lnproxy/lnproxy-relay#7]
By combining the wrapped invoices with a LN Address bridge server, the server could easily serve as an automatic proxy for every transaction created for that node.

User would only need to share his LN address to provide a wrapped invoice for that bridge's node.

Maybe could be integrated into:
https://github.com/nbd-wtf/satdress

**Comment by lnproxy** [comment]
So the person hosting the LN Address bridge server would use the lnproxy api to hide their node's pubkey?
I think I like it but I'll have to think more.

**Comment by bitcoinheiro** [comment]
The LN address bridge node would be the proxy for the user node.
The bridge forwards to a node. So in this forwarding process, it could create a LNProxy invoice using the bridge node, so people paying have no clue about the actual final destination node.

LN Address Bridge service + LNProxy would be lit.
Easy private wrapped invoices with simple UX, just share a LNaddress so people can pay you privately.

Yesterday the guys from ZBD (they sponsor satdress) launched an open source initiative (grants) - maybe this project could grab a grant - https://nbd.wtf/

**Comment by lnproxy** [comment]
Oh I see.  I don't think I understood the purpose of the bridge server.  So someone that owns a domain hosts this server that takes invoice macaroons from people's nodes and gives them back a lightning address which they can use to get paid.  I suppose you kinda have to trust the bridge server already not give out an invoice for someone else, but if you can trust them then yeah this makes a lot of sense.

That being said, I probably wouldn't trust such a service with much volume.  Definitely better to host your own lightning address server on your domain so that you know people that pay you always get an invoice that will send funds to your node.  Or maybe I'm missing something..

Anyway, I do think the self hosted solution is pretty damn valuable, I'll work on that.

**Comment by bitcoinheiro** [comment]
Great! Yeah, I was thinking that the LN Bridge with a trusted third party would only make sense to me if it could also provide me some privacy from other third parties. Still, having an automatic buffer between my own domain/server and my lightning node is also valuable, I totally agree.

In that case, I would need to be running 2 nodes, right?
One on the LNProxy-Address-bridge and also my personal private node

**Comment by lnproxy** [comment]
No you would just run your normal node and a little binary server that would automatically talk to lnproxy and make sure that the hashes always matched for you.  Then you could give people your lightning address (something like `bitcoinheiro@bitcoinheiro.com`) and not have to trust anyone with funds.

**Comment by lnproxy** [comment]
Please see this repo https://github.com/lnproxy/lnproxy-address for a tool with this use case in mind.
